# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "cordova"
    vb.memory = "2048"
  end
  config.vm.provision "shell", path: "provision.sh"

  Dir.foreach('..') do |item|
    next if item == '.' or item == '..' or !File.directory?("../"+item)
    config.vm.synced_folder "../"+item, "/home/vagrant/"+item
  end

  config.ssh.forward_agent = true
end
